version: "3.8"

services:  
  go-application:
    container_name: go-application
    build: .
    ports: 
      - 8081:8080
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=Mbahbambang123
      - DB_DB=miniproject
      - DB_HOST=valiant-carrier-385811:asia-southeast2:miniprojectdb
      - DB_PORT=3306
    restart: on-failure